[package]
name = "moodl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "moodl-rs"
path = "src/main.rs"


[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.185"
serde_derive = "1.0.185"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
scraper ="0.17.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }

[dev-dependencies]
mockito = "1.1.0"
